<?php

namespace Lvlapc\Authentication\Model;

use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\ResultInterface;
use Phalcon\Mvc\Model\ResultSetInterface;

/**
 * CookieToken
 *
 * @autogenerated by Phalcon Developer Tools
 */
class CookieToken extends Model
{
	/**
	 *
	 * @var integer
	 */
	protected $id;

	/**
	 *
	 * @var string
	 */
	protected $token;

	/**
	 *
	 * @var integer
	 */
	protected $user_id;

	/**
	 *
	 * @var string
	 */
	protected $created_at;

	/**
	 * Allows to query a set of records that match the specified conditions
	 *
	 * @param mixed $parameters
	 * @return CookieToken[]|CookieToken|ResultSetInterface
	 */
	public static function find($parameters = null)
	{
		return parent::find($parameters);
	}

	/**
	 * Allows to query the first record that match the specified conditions
	 *
	 * @param mixed $parameters
	 * @return CookieToken|ResultInterface
	 */
	public static function findFirst($parameters = null)
	{
		return parent::findFirst($parameters);
	}

	/**
	 * Returns the value of field id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Method to set the value of field id
	 *
	 * @param integer $id
	 * @return $this
	 */
	public function setId($id)
	{
		$this->id = $id;

		return $this;
	}

	/**
	 * Returns the value of field token
	 *
	 * @return string
	 */
	public function getToken()
	{
		return $this->token;
	}

	/**
	 * Method to set the value of field token
	 *
	 * @param string $token
	 * @return $this
	 */
	public function setToken($token)
	{
		$this->token = $token;

		return $this;
	}

	/**
	 * Returns the value of field user_id
	 *
	 * @return integer
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Method to set the value of field user_id
	 *
	 * @param integer $user_id
	 * @return $this
	 */
	public function setUserId($user_id)
	{
		$this->user_id = $user_id;

		return $this;
	}

	/**
	 * Returns the value of field created_at
	 *
	 * @return string
	 */
	public function getCreatedAt()
	{
		return $this->created_at;
	}

	/**
	 * Method to set the value of field created_at
	 *
	 * @param string $created_at
	 * @return $this
	 */
	public function setCreatedAt($created_at)
	{
		$this->created_at = $created_at;

		return $this;
	}

	/**
	 * Initialize method for model.
	 */
	public function initialize()
	{
		$this->setSource("cookie_token");

		$this->skipAttributesOnCreate(['created_at']);
	}
}